# Generated by Django 4.1.2 on 2022-10-21 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='post',
            new_name='Post',
        ),
        migrations.RenameField(
            model_name='log',
            old_name='userid',
            new_name='Userid',
        ),
    ]
