# Generated by Django 4.1.2 on 2022-10-22 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_log_userid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='Post',
        ),
        migrations.RemoveField(
            model_name='log',
            name='Userid',
        ),
        migrations.AddField(
            model_name='log',
            name='post',
            field=models.CharField(default='User', max_length=20),
        ),
        migrations.AddField(
            model_name='log',
            name='userid',
            field=models.CharField(default='7', max_length=115, primary_key=True, serialize=False),
        ),
    ]
