# Generated by Django 4.1.2 on 2022-10-29 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('profilepic', models.ImageField(null=True, upload_to='myapp/images')),
                ('userid', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('bio', models.TextField(null=True)),
                ('skills', models.TextField(null=True)),
                ('facebook', models.URLField(null=True)),
                ('twitter', models.URLField(null=True)),
                ('instagram', models.URLField(null=True)),
                ('linkedin', models.URLField(null=True)),
            ],
        ),
    ]
