# Generated by Django 4.1.2 on 2022-11-01 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='startup',
            fields=[
                ('profilepic', models.ImageField(blank=True, null=True, upload_to='myapp/images')),
                ('coverphoto', models.ImageField(blank=True, null=True, upload_to='myapp/images')),
                ('startupid', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('websitelink', models.TextField(blank=True, null=True)),
                ('pitch', models.ImageField(blank=True, null=True, upload_to='myapp/images')),
                ('about', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
