# Generated by Django 4.1.2 on 2022-11-02 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_startup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='startup',
            name='email',
        ),
        migrations.AlterField(
            model_name='startup',
            name='coverphoto',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='startup',
            name='pitch',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='startup',
            name='profilepic',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='startup',
            name='websitelink',
            field=models.URLField(blank=True, null=True),
        ),
    ]
