# Generated by Django 4.1.2 on 2022-11-04 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_remove_startup_email_alter_startup_coverphoto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='suggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('to', models.CharField(max_length=30)),
                ('by', models.CharField(max_length=30)),
                ('opinion', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
