# Generated by Django 4.1.2 on 2022-11-04 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_suggestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestion',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
