# Generated by Django 4.1.2 on 2022-11-13 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_rename_websitelink_startup_startuplink_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='post_id',
            field=models.IntegerField(default=0),
        ),
    ]
