# Generated by Django 4.1.2 on 2022-11-14 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_alter_entrepreneur_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startup',
            name='form',
            field=models.URLField(blank=True, default='https://www.linkedin.com/feed/', null=True),
        ),
    ]
