# Generated by Django 4.1.2 on 2022-11-14 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_alter_startup_form'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=500)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('userid', models.CharField(max_length=30)),
                ('post_id', models.CharField(default=0, max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='image',
            name='post_id',
        ),
    ]
