# Generated by Django 4.1.2 on 2022-11-18 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_alter_comment_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrepreneur',
            name='facebook',
            field=models.URLField(blank=True, default='https://www.linkedin.com/feed/', null=True),
        ),
        migrations.AlterField(
            model_name='entrepreneur',
            name='instagram',
            field=models.URLField(blank=True, default='https://www.linkedin.com/feed/', null=True),
        ),
        migrations.AlterField(
            model_name='entrepreneur',
            name='linkedin',
            field=models.URLField(blank=True, default='https://www.linkedin.com/feed/', null=True),
        ),
        migrations.AlterField(
            model_name='entrepreneur',
            name='twitter',
            field=models.URLField(blank=True, default='https://www.linkedin.com/feed/', null=True),
        ),
        migrations.AlterField(
            model_name='nuser',
            name='facebook',
            field=models.URLField(blank=True, default='https://www.linkedin.com/feed/', null=True),
        ),
        migrations.AlterField(
            model_name='nuser',
            name='instagram',
            field=models.URLField(blank=True, default='https://www.linkedin.com/feed/', null=True),
        ),
        migrations.AlterField(
            model_name='nuser',
            name='linkedin',
            field=models.URLField(blank=True, default='https://www.linkedin.com/feed/', null=True),
        ),
        migrations.AlterField(
            model_name='nuser',
            name='twitter',
            field=models.URLField(blank=True, default='https://www.linkedin.com/feed/', null=True),
        ),
        migrations.AlterField(
            model_name='startup',
            name='facebook',
            field=models.URLField(blank=True, default='https://www.linkedin.com/feed/', null=True),
        ),
        migrations.AlterField(
            model_name='startup',
            name='instagram',
            field=models.URLField(blank=True, default='https://www.linkedin.com/feed/', null=True),
        ),
        migrations.AlterField(
            model_name='startup',
            name='linkedin',
            field=models.URLField(blank=True, default='https://www.linkedin.com/feed/', null=True),
        ),
        migrations.AlterField(
            model_name='startup',
            name='twitter',
            field=models.URLField(blank=True, default='https://www.linkedin.com/feed/', null=True),
        ),
    ]
